[package]
name = "task1"
version = "1.0.0"
authors = []

[addresses]
hello_world="0x7001306d411a24cd2a43b9af7d77e88ae53c41b50126d1e86fe20a30892ba1f6"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
