[package]
name = "task1"
version = "1.0.0"
authors = []

[addresses]
hello_world = "0xd62342f88b640118205d008114883ef14665084f66dec860e539bc0c95d7b6e2"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
